---

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.3.0
    driver_plugin: docker
    driver_config:
      image: rosstimson/debian:wheezy
      platform: debian
  - name: centos-6.5
    driver_plugin: docker
    driver_config:
      image: rosstimson/centos:6.5
      platform: centos

suites:
  - name: default
    run_list:
      - recipe[rosstimson::default]
